### ISSUE TITLE
Pin to numpy~=1.17 (satisfying aiida-core)

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-optimade#2]
From @yakutovicha:

> Please modify the numpy dependency version, which currently looks as:
> https://github.com/CasperWA/voila-optimade-client/blob/706ab1f48914db8a1ea69f9f59507285449730ce/requirements.txt#L8
>
> to `>=1.17`, so that they can be installed with `aiida-core[atomic_tools]` in the same environment without conflicts.
>
> _Originally from CasperWA/voila-optimade-client#156 opened by @yakutovicha_

**Comment by CasperWA** [comment]
More to the point, the requirement needs to be `<1.18`. If set to `~=1.17` nothing would change compared to the current dependencies since `~=1.17` is equivalent to `>=1.17,<2.0`.
To solve this, the requirement should be `~=1.17.0`, which would mean `>=1.17.0,<1.18`.

Furthermore, instead of using `1.17.0` we can use `1.17.5`, since this is the `numpy` version used in the requirements files for `aiida-core` for all the supported Python versions (3.5-3.8). [Here's a link](https://github.com/aiidateam/aiida-core/blob/b002a9a9a898a05338ff522b46686657fb468f66/requirements/requirements-py-3.5.txt#L65) to the `numpy` line in the requirements files for the oldest Python version (3.5).

**Comment by yakutovicha** [comment]
> More to the point, the requirement needs to be `<1.18`. If set to `~=1.17` nothing would change compared to the current dependencies since `~=1.17` is equivalent to `>=1.17,<2.0`.

I think this is not true. If you set `numpy` to be either `~=1.17` or to `>=1.17.0,<1.18` the dependency resolver would select `1.17.5` wich works for both: `aiida-core` and (hopefully) for the `optimade-client`.

**Comment by CasperWA** [comment]
> > More to the point, the requirement needs to be `<1.18`. If set to `~=1.17` nothing would change compared to the current dependencies since `~=1.17` is equivalent to `>=1.17,<2.0`.
> 
> I think this is not true. If you set `numpy` to be either `~=1.17` or to `>=1.17.0,<1.18` the dependency resolver would select `1.17.5` wich works for both: `aiida-core` and (hopefully) for the `optimade-client`.

[This](https://www.python.org/dev/peps/pep-0440/#compatible-release) is the definition of `~=`. It only respects the accuracy of the written version, i.e., `~=1.17` becomes `>=1.17,<2.0`, while `~=1.17.0` becomes `>=1.17.0,<1.18`. I am pretty sure of this as I have tested this extensively.

The confusion may arise from including other dependencies and dependencies of dependencies. It _may_ be that `pip` will install `1.17.5` due to the dependency of `aiida-core` (where it is explicitly set to `>=1.17,<1.18`), while the dependency in `aiidalab-optimade` could be set to `~=1.17`. However, this is not clear from the point-of-view of installing `aiidalab-optimade`, hence it would be better to properly reflect the `aiida-core` dependency and write `~=1.17.0` (or `~=1.17.5` for the reasons explained above). I hope that this is clearer?

**Comment by yakutovicha** [comment]
> [This](https://www.python.org/dev/peps/pep-0440/#compatible-release) is the definition of `~=`. It only respects the accuracy of the written version, i.e., `~=1.17` becomes `>=1.17,<2.0`, while `~=1.17.0` becomes `>=1.17.0,<1.18`. I am pretty sure of this as I have tested this extensively.

I totally agree.

> The confusion may arise from including other dependencies and dependencies of dependencies. 

When I build the environment, I verify all the dependencies, and the dependencies of the dependencies. It is explained [here](https://github.com/aiidalab/aiidalab#updating-requirements). With this approach, we have no confusions.

The only problem now is: `aiida-core` needs `numpy<0.18`, while the optimade client needs `numpy>=0.19`.

**Comment by CasperWA** [comment]
> When I build the environment, I verify all the dependencies, and the dependencies of the dependencies. It is explained [here](https://github.com/aiidalab/aiidalab#updating-requirements). With this approach, we have no confusions.
> 
> The only problem now is: `aiida-core` needs `numpy<0.18`, while the optimade client needs `numpy>=0.19`.

Cheers, this clears things up a bit for me in this discussion.
I am still unsure what the best approach is here. Either the range of allowed numpy versions should be extended in `optimade-client` as you suggest or we should push to get `aiida-core` updated to the latest numpy version.

**Comment by yakutovicha** [comment]
> I am still unsure what the best approach is here.

I think changing the numpy dependency for the optimade client would be wiser. Because this would show that your client is capable of working with a wider range of versions, and not just the latest ones.

**Comment by CasperWA** [comment]
Made redundant with an update to AiiDA Core.
