### ISSUE TITLE
Deprecate OptimadeQueryWidget

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-optimade#4]
The `OptimadeQueryWidget` is moving over to `aiidalab-widgets-base` (aiidalab/aiidalab-widgets-base#131). To keep a grace period, the widget will be imported from `aiidalab-widgets-base` and still be importable from this application, but with a deprecation warning.

**Comment by csadorf** [comment]
Can you remind me where we made the decision for this move? As I commented on the other PR, I am not sure that this makes sense.
